"use client";
import Image from "next/image";
import { motion, useReducedMotion } from "framer-motion";
import type { CSSProperties } from "react";
import type { Domain } from "./domains";

export function DomainPod({ domain, active, dimmed, onSelect, onMouseEnter, onMouseLeave }: { domain: Domain; active: boolean; dimmed: boolean; onSelect: () => void; onMouseEnter?: () => void; onMouseLeave?: () => void }) {
  const reduceMotion = useReducedMotion();
  return <motion.button type="button" onClick={onSelect} onHoverStart={onMouseEnter} onHoverEnd={onMouseLeave} aria-pressed={active} aria-label={`Open ${domain.title} domain`} className="group relative h-[29rem] w-full min-w-[17.5rem] flex-1 overflow-hidden rounded-sm text-left outline-none focus-visible:ring-2 focus-visible:ring-cyan-200 md:h-[33rem] md:min-w-0 lg:h-[25rem] xl:h-[28rem]" style={{ "--accent": domain.accent } as CSSProperties} initial={{ opacity: 0, y: 36 }} animate={{ opacity: dimmed ? .32 : 1, y: 0, scale: active ? 1.025 : 1, filter: dimmed ? "blur(2px) brightness(.45)" : "blur(0) brightness(1)" }} transition={{ type: "spring", stiffness: 110, damping: 18, delay: domain.variation * .1 }} whileHover={reduceMotion ? undefined : { y: -7 }}>
    <div className="absolute inset-x-5 inset-y-0 border-x-4 border-stone-800/40 bg-gradient-to-b from-[#1a1512] via-[#0d0a08] to-black/80" /><div className="absolute inset-x-4 top-0 h-4 border-x-4 border-t-4 border-stone-800/60 bg-[#2d2520]" /><div className="absolute inset-x-2 bottom-3 h-12 border-2 border-stone-700/30 bg-gradient-to-b from-[#3d332d] to-[#14100e] shadow-[0_12px_24px_rgba(0,0,0,.8)]" /><div className="absolute inset-x-6 bottom-12 h-14 rounded-[50%] bg-[var(--accent)]/5 blur-xl transition-all duration-700 group-hover:bg-[var(--accent)]/30 group-hover:blur-2xl" /><div className="absolute inset-x-5 top-4 h-[70%] bg-gradient-to-b from-[var(--accent)]/40 via-[var(--accent)]/10 to-transparent opacity-0 mix-blend-screen transition-opacity duration-700 group-hover:opacity-100" /><motion.div className="absolute inset-y-6 left-[18%] w-px bg-[var(--accent)] opacity-20 shadow-[0_0_15px_var(--accent)]" animate={reduceMotion ? undefined : { opacity: [.1, .4, .1] }} transition={{ duration: 3.2, repeat: Infinity }} /><motion.div className="absolute inset-x-7 bottom-10 top-12" animate={reduceMotion ? undefined : { y: [0, -5, 0] }} transition={{ duration: 4.5 + domain.variation, repeat: Infinity, ease: "easeInOut" }}><Image src={domain.image} alt={domain.character} fill sizes="(max-width: 640px) 76vw, (max-width: 1024px) 40vw, 25vw" className="object-contain object-bottom drop-shadow-[0_20px_15px_rgba(0,0,0,1)] transition-all duration-700 brightness-[0.4] grayscale-[60%] sepia-[40%] contrast-125 group-hover:scale-[1.05] group-hover:brightness-[1.15] group-hover:grayscale-0 group-hover:sepia-0 group-hover:drop-shadow-[0_0_25px_var(--accent)]" priority={domain.variation < 2} /></motion.div><div className="absolute inset-x-5 top-0 h-full bg-gradient-to-br from-[#594a42]/[.08] via-transparent to-transparent opacity-70" /><div className="absolute left-7 top-9 font-mono text-[9px] font-bold tracking-[.24em] text-[#d6c5b3]/40 transition-colors duration-500 group-hover:text-[var(--accent)]">EXPEDITION–0{domain.variation + 1} / PREPARING</div><div className="absolute inset-x-7 bottom-7 translate-y-2 opacity-60 transition-all duration-500 group-hover:translate-y-0 group-hover:opacity-100"><p className="font-mono text-[9px] tracking-[.2em] text-[#d6c5b3]/70 group-hover:text-[var(--accent)]">SECTOR {domain.variation + 1} // {domain.character.toUpperCase()}</p><h3 className="mt-1 text-2xl font-black uppercase tracking-tighter text-[#f2e6d9] drop-shadow-md group-hover:text-white group-hover:drop-shadow-[0_0_10px_var(--accent)]">{domain.title}</h3></div>
    {active && <><motion.div className="absolute inset-y-3 left-5 w-[calc(50%-1.25rem)] border-r border-stone-600/30 bg-[#2d2520]/60 backdrop-blur-sm" initial={{ x: 0, opacity: .9 }} animate={{ x: "-43%", opacity: 0 }} transition={{ duration: .7, ease: [0.22, 1, .36, 1] }} /><motion.div className="absolute inset-y-3 right-5 w-[calc(50%-1.25rem)] border-l border-stone-600/30 bg-[#2d2520]/60 backdrop-blur-sm" initial={{ x: 0, opacity: .9 }} animate={{ x: "43%", opacity: 0 }} transition={{ duration: .7, ease: [0.22, 1, .36, 1] }} /><motion.div layoutId="active-pod" className="absolute inset-0 border-2 border-[var(--accent)] shadow-[inset_0_0_40px_var(--accent)]" /></>}
  </motion.button>;
}
