"use client";
import { useEffect, useState } from "react";
import { motion, useReducedMotion } from "framer-motion";
import { BackgroundEffects } from "./BackgroundEffects";
import { DomainInfoPanel } from "./DomainInfoPanel";
import { DomainPod } from "./DomainPod";
import { domains, type Domain } from "./domains";

export function DomainsSection() { const [selected, setSelected] = useState<Domain | null>(null); const [hoveredDomain, setHoveredDomain] = useState<Domain | null>(null); const reduced = useReducedMotion(); useEffect(() => { const close = (event: KeyboardEvent) => event.key === "Escape" && setSelected(null); window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, []); return <section id="domains" className="relative isolate min-h-screen overflow-hidden bg-[#0a0806] px-4 py-12 text-[#f2e6d9] sm:px-8 lg:flex lg:h-screen lg:min-h-[42rem] lg:items-center lg:px-12 lg:py-7" aria-labelledby="domains-title"><BackgroundEffects /><div className="absolute inset-0 transition-all duration-700 pointer-events-none mix-blend-screen" style={{ backgroundColor: hoveredDomain ? hoveredDomain.accent : 'transparent', opacity: hoveredDomain ? 0.25 : 0 }} /><div className="relative z-10 mx-auto w-full max-w-[96rem]"><motion.header initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: reduced ? 0 : .7 }} className="mb-8 flex items-end justify-between gap-6 lg:mb-5"><div><h1 id="domains-title" className="mt-3 text-4xl font-black uppercase leading-none tracking-[-.04em] sm:text-6xl lg:text-6xl xl:text-7xl">Choose your<br /><span className="text-red-800">Survey Corps.</span></h1><p className="mt-3 max-w-md text-sm text-stone-300/75">Every mission begins with a choice. Select your battlefield.</p></div><p className="hidden text-right font-mono text-[10px] leading-5 tracking-widest text-stone-400/35 md:block">04 DOMAINS<br />ONE HUMANITY</p></motion.header><div className="-mx-4 flex snap-x snap-mandatory gap-3 overflow-x-auto px-4 pb-3 [scrollbar-width:none] md:mx-0 md:grid md:grid-cols-2 md:overflow-visible md:px-0 lg:grid-cols-4">{domains.map((domain) => <div key={domain.id} className="snap-center md:min-w-0"><DomainPod domain={domain} active={selected?.id === domain.id} dimmed={Boolean(selected && selected.id !== domain.id)} onSelect={() => setSelected((current) => current?.id === domain.id ? null : domain)} onMouseEnter={() => setHoveredDomain(domain)} onMouseLeave={() => setHoveredDomain(null)} /></div>)}</div></div><DomainInfoPanel domain={selected} onClose={() => setSelected(null)} /></section>; }
